# Generated by Django 4.2.4 on 2023-09-19 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userprofile_groups_userprofile_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('paper_name', models.CharField(max_length=255, null=True)),
                ('paper_description', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
