# Generated by Django 4.2.4 on 2023-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_papers_file_papers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal'), ('article', 'Article')], default='journal', max_length=20),
        ),
    ]
