# Generated by Django 4.2.4 on 2023-09-19 12:16

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_papers_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(help_text='Upload only .pdf files.', upload_to='media/%Y/%m/%d', validators=[website.models.validate_paper_type]),
        ),
    ]
